export const SAMPLE_PORTFOLIO = {
  net_worth: 5500000,
  total_invested: 5000000,
  total_gain: 500000,
  total_gain_percent: 10.0,
  total_commission_loss: 15000,
  portfolio_health_score: 78,
  funds_count: 5,
  direct_funds_count: 4,
  regular_funds_count: 1,
  asset_allocation: {
    Equity: 80,
    Debt: 15,
    Gold: 5,
  },
  funds: [
    {
      name: "HDFC Flexi Cap Fund - Direct",
      category: "Flexi Cap",
      value: 1725000,
      invested: 1500000,
      plan_type: "Direct",
      xirr: 15.2,
      xirr_status: "Calculated",
      rating: "On-Track",
      annual_commission_loss: 0,
      amc: "HDFC",
      folio: "HDFC001234567",
    },
    {
      name: "Parag Parikh Flexi Cap Fund - Regular",
      category: "Flexi Cap",
      value: 1377600,
      invested: 1200000,
      plan_type: "Regular",
      xirr: 14.8,
      xirr_status: "Calculated",
      rating: "Off-Track",
      annual_commission_loss: 18000,
      amc: "PPFAS",
      folio: "PPFAS00234567",
      warning: "Switch to Direct Plan - Save Rs.18,000/year",
    },
    {
      name: "Axis Bluechip Fund - Direct",
      category: "Large Cap",
      value: 1135000,
      invested: 1000000,
      plan_type: "Direct",
      xirr: 13.5,
      xirr_status: "Calculated",
      rating: "On-Track",
      annual_commission_loss: 0,
      amc: "Axis",
      folio: "AXIS00345678",
    },
    {
      name: "Mirae Asset Emerging Bluechip - Direct",
      category: "Large & Mid Cap",
      value: 934400,
      invested: 800000,
      plan_type: "Direct",
      xirr: 16.8,
      xirr_status: "Calculated",
      rating: "On-Track",
      annual_commission_loss: 0,
      amc: "Mirae Asset",
      folio: "MIRAE0456789",
    },
    {
      name: "Kotak Small Cap Fund - Direct",
      category: "Small Cap",
      value: 592500,
      invested: 500000,
      plan_type: "Direct",
      xirr: 18.5,
      xirr_status: "Calculated",
      rating: "On-Track",
      annual_commission_loss: 0,
      amc: "Kotak",
      folio: "KOTAK0567890",
    },
  ],
  overlaps: [
    {
      stock: "Reliance Industries",
      funds: ["HDFC Flexi Cap", "Parag Parikh Flexi Cap", "Axis Bluechip"],
      totalExposure: 8.5,
    },
  ],
  recommendations: [
    "Switch Parag Parikh Flexi Cap from Regular to Direct - Save Rs.18,000 annually",
    "High overlap detected in Large Cap stocks - Consider diversifying",
    "Your portfolio is overweight in Flexi Cap (54%) - Consider rebalancing",
  ],
};
