export const SAMPLE_PORTFOLIO = {
  net_worth: 750000,
  total_invested: 580000,
  total_gain: 170000,
  total_gain_percent: 29.31,
  total_commission_loss: 8700,
  portfolio_health_score: 72,
  funds_count: 8,
  direct_funds_count: 3,
  regular_funds_count: 5,
  asset_allocation: {
    Equity: 65,
    Debt: 25,
    Gold: 10,
  },
  funds: [
    {
      name: "ICICI Prudential Mid Cap Growth Fund - Regular",
      category: "Mid Cap Equity",
      value: 125000,
      invested: 95000,
      plan_type: "Regular",
      xirr: 18.5,
      xirr_status: "Calculated",
      rating: "On-Track",
      annual_commission_loss: 1250,
      amc: "ICICI Prudential",
      folio: "IPRU0001234567",
    },
    {
      name: "HDFC Bank - Direct",
      category: "Large Cap Equity",
      value: 156000,
      invested: 120000,
      plan_type: "Direct",
      xirr: 22.3,
      xirr_status: "Calculated",
      rating: "On-Track",
      annual_commission_loss: 0,
      amc: "HDFC",
      folio: "HDFC0002345678",
    },
    {
      name: "Axis Liquid Fund - Regular",
      category: "Liquid Fund",
      value: 85000,
      invested: 83000,
      plan_type: "Regular",
      xirr: 6.2,
      xirr_status: "Calculated",
      rating: "Off-Track",
      annual_commission_loss: 850,
      amc: "Axis",
      folio: "AXIS0003456789",
    },
    {
      name: "SBI Balanced Advantage Fund - Direct",
      category: "Balanced",
      value: 142000,
      invested: 105000,
      plan_type: "Direct",
      xirr: 14.8,
      xirr_status: "Calculated",
      rating: "On-Track",
      annual_commission_loss: 0,
      amc: "SBI",
      folio: "SBI00004567890",
    },
    {
      name: "Reliance Pharma Fund - Regular",
      category: "Sectoral",
      value: 98000,
      invested: 87000,
      plan_type: "Regular",
      xirr: 12.1,
      xirr_status: "Calculated",
      rating: "Off-Track",
      annual_commission_loss: 980,
      amc: "Reliance",
      folio: "RELI0005678901",
    },
    {
      name: "Kotak Emerging Opportunities Fund - Regular",
      category: "Multi Cap",
      value: 92000,
      invested: 72000,
      plan_type: "Regular",
      xirr: 19.5,
      xirr_status: "Calculated",
      rating: "On-Track",
      annual_commission_loss: 920,
      amc: "Kotak",
      folio: "KOTA0006789012",
    },
    {
      name: "UTI Gilt Fund - Direct",
      category: "Debt",
      value: 108000,
      invested: 98000,
      plan_type: "Direct",
      xirr: 5.8,
      xirr_status: "Calculated",
      rating: "On-Track",
      annual_commission_loss: 0,
      amc: "UTI",
      folio: "UTI00007890123",
    },
    {
      name: "ICICI Gold ETF - Regular",
      category: "Gold",
      value: 94000,
      invested: 73000,
      plan_type: "Regular",
      xirr: 11.2,
      xirr_status: "Calculated",
      rating: "On-Track",
      annual_commission_loss: 940,
      amc: "ICICI",
      folio: "GOLD0008901234",
    },
  ],
};
